######################################################################
# Automatically generated by qmake (2.00a) Sat Feb 3 14:09:09 2007
######################################################################

TEMPLATE = app
TARGET += 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += oct_sim.h \
           Point.h \
           TransMatrix.h \
           Volume.h \
           dbh.h 
SOURCES += main.cpp \
           oct_sim.cpp \
           Point.cpp \
           TransMatrix.cpp \
           Volume.cpp \
           dbh.cpp 

CONFIG += release
